# Generated by Django 4.2.1 on 2023-06-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Secondname', models.CharField(max_length=100)),
                ('Emailaddress', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('customerID', models.IntegerField()),
            ],
        ),
    ]
