# Generated by Django 4.2.3 on 2023-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Emailaddress',
            new_name='emailaddress',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Secondname',
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
