# Generated by Django 4.2.1 on 2023-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='list_of_items',
            field=models.IntegerField(),
        ),
    ]
