# Generated by Django 4.2.3 on 2023-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=1, upload_to='cart_images/'),
            preserve_default=False,
        ),
    ]
