# Generated by Django 4.2.1 on 2023-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_ID', models.IntegerField()),
            ],
        ),
    ]
